module.exports = [
	{
		path:'settings',
		controller:{},
		middleware:[
			require('../controllers/settingspermissions')
		],
		data:{
			id:'settingID',
			model:'Settings',
			required:[
				'name'
			],
			optional:[
				'description',
				'ownerID',
				'public',
				'unrestricted'
			],
			public:[
				'id',
				'name',
				'description',
				'ownerID',
				'public',
				'unrestricted'
			],
			req:[
				{
					name:'ownerID',
					hierarchy:[
						'user',
						'id'
					]
				}
			]
		},
		children:[
			{
				path:'people',
				data:{
					id:'personID',
					belongsTo:'settingID',
					model:'People',
					required:[
						'name'
					],
					optional:[
						'profession',
						'appearance',
						'personality',
						'history'
					],
					public:[
						'id',
						'name',
						'appearance',
						'personality',
						'history'
					]
				}
			},
			{
				path:'locations',
				data:{
					id:'locationID',
					belongsTo:'settingID',
					model:'Locations',
					required:[
						'name'
					],
					optional:[
						'type',
						'description',
						'history',
						'population',
						'populationDensity',
						'crime',
						'wealth'
					],
					public:[
						'id',
						'name',
						'type',
						'description',
						'history',
						'population',
						'populationDensity',
						'crime',
						'wealth'
					]
				}
			},
			{
				path:'civilizations',
				data:{
					id:'civilizationID',
					belongsTo:'settingID',
					model:'Civilizations',
					required:[
						'name'
					],
					optional:[
						'description'
					],
					public:[
						'id',
						'name',
						'description',
						'settingID'
					]
				}
			},
			{
				path:'items',
				data:{
					id:'itemID',
					belongsTo:'settingID',
					model:'Items',
					required:[
						'name'
					],
					optional:[
						'type',
						'appearance',
						'history'
					],
					public:[
						'id',
						'name',
						'type',
						'appearance',
						'history'
					]
				}
			},
			{
				path:'events',
				data:{
					id:'eventID',
					belongsTo:'settingID',
					model:'Events',
					required:[
						'name'
					],
					optional:[
						'type',
						'year',
						'description'
					],
					public:[
						'id',
						'name',
						'type',
						'year',
						'description'
					]
				}
			},
			{
				path:'races',
				data:{
					id:'raceID',
					belongsTo:'settingID',
					model:'Races',
					required:[
						'name'
					],
					optional:[
						'description',
						'appearance'
					],
					public:[
						'id',
						'name',
						'description',
						'appearance'
					]
				}
			},
			{
				path:'creatures',
				data:{
					id:'creatureID',
					belongsTo:'settingID',
					model:'Creatures',
					required:[
						'name'
					],
					optional:[
						'description',
						'history'
					],
					public:[
						'id',
						'name',
						'description',
						'history'
					]
				}
			},
			{
				path:'species',
				data:{
					id:'speciesID',
					belongsTo:'settingID',
					model:'Species',
					required:[
						'name'
					],
					optional:[
						'description',
						'appearance'
					],
					public:[
						'id',
						'name',
						'description',
						'appearance'
					]
				}
			},
			{
				path:'spirits',
				data:{
					id:'spiritID',
					belongsTo:'settingID',
					model:'Spirits',
					required:[
						'name'
					],
					optional:[
						'type',
						'description',
						'history',
						'unique'
					],
					public:[
						'id',
						'name',
						'description',
						'history',
						'unique'
					]
				}
			}
		]
	},
	{
		path:'users',
		id:'userID'
	}
];